version: "3"

services:
  
  template-api:
    container_name: "template-api"
    build: .
    tty: true
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - template-db
    volumes:
      - type: bind
        source: .
        target: /api

  template-db:
    image: postgres:14-alpine
    container_name: template-db
    ports: 
      - "9001:5432"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
