version: "3"

services:
  
  api:
    container_name: "nest_api_container"
    build: .
    tty: true
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - ts-database
    volumes:
      - type: bind
        source: .
        target: /api

  ts-database:
    image: postgres:14-alpine
    container_name: ts-database
    ports: 
      - "9001:5432"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts-database
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    volumes:
      - ./script:/docker-entrypoint-initdb.d/
